name: Build and Release

on:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
        os_name: ${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'win' || 'mac' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install .
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile pdf_suite/cli.py -n pdf_suite

      - name: Flatten binary for upload
        run: |
          mv dist/pdf_suite pdf_suite-${{ env.os_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf_suite-binaries
          path: pdf_suite-*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdf_suite-binaries
          path: ./binaries

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh

      - name: Upload binaries to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_BINARIES }}
        run: |
          for file in ./binaries/**/*; do
            ls -la "$file"
          done
