name: Build and Release

on:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.11]
    env:
        os_name: ${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'win' || 'mac' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install .
          pip install pyinstaller

      - name: export

      - name: Build binary
        run: |
          pyinstaller --onefile pdf_suite/cli.py -n pdf_suite-${{ env.os_name }}
        env:
          PYINSTALLER_NO_PYTHONLIB: ${{ runner.os_name == 'linux' && '1' || ''}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf_suite-${{ env.os_name }}
          path: dist/pdf_suite-${{ env.os_name }}*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./binaries

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh

      - name: Upload binaries to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_BINARIES }}
        run: |
          for file in ./binaries/**/*; do
            gh release upload v0.4.2 "$file" --clobber
          done
